### ISSUE TITLE
Unclear usage of "musicPath" and "musicPathOrig"

### ISSUE THREAD

**Issue by samba2** [ericdaugherty/itunesexport-go#10]
I'd like to do the following:

````
itunesexport64.exe -library "\\192.168.178.3\maik\itunes\Mediathek.xml" -output c:\temp -includePlaylistWithRegex ".+Mandingo.+" -copy PLAYLIST -musicPath '\\192.168.178.3\maik\itunes' -musicPathOrig /192.168.178.3/maik/itunes
````

So the idea is that in the "Location", "/192.168.178.3/maik/itunes" is replaced with "'\\192.168.178.3\maik\itunes'. However, these parameters only seem to have an effect [when the copy mode is NONE](https://github.com/ericdaugherty/itunesexport-go/blob/master/export.go#L144). Is there a reason for that? What is the intent of these params?

I was able to get the example running by copying the `strings.Replace` call into [here ](https://github.com/ericdaugherty/itunesexport-go/blob/master/export.go#L137 )so it could work but I am not sure if I understand the reasoning behind the params correctly.

**Comment by ericdaugherty** [comment]
Thanks for the PRs. I think this is addressed but let me know if you still have questions.

**Comment by samba2** [comment]
Thanks Eric for the quick review and approval 👍

**Comment by Andrrison** [comment]
Is this update a way to achieve having a backslash instead of a forward slash in output file pathways, as requested in [https://github.com/ericdaugherty/itunesexport-go/issues/6](url)?

If not, what can this update enable now (apologies, I didn't understand the use case provided)?

Thanks
