### ISSUE TITLE
Missing musicPath parameter

### ISSUE THREAD

**Issue by newkind** [ericdaugherty/itunesexport-go#4]
Hi!

First of all thank you very much for your app! It really helps me to keep my Music/iTunes library in sync with my Synology NAS! :)

I just wanted to report a missing native app feature for modifying the music file location path.

In the original JAVA version you could do:

```
-musicPath="../Music/"
```

To change all of the files paths in the generated M3U files. This is not possible with the new app.

Thanks!

**Comment by ericdaugherty** [comment]
Released v1.1.0 that adds this feature back in. Let me know if it works as expected.

**Comment by newkind** [comment]
Seems to work perfect! Thank you so much!
